[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "17.2.0"

[build]
  publish = "build"
  command = "npm i && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
